title:            Notes by Amit Solanki
description:      I write here. 
url:              # Site url.
signoff:          Amit Solanki
disqus_shortname: fashsolanki
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: UA-41949970-3

links:
  - name:         About
    url:          /about
  - name:         Email
    url:          mailto:amit@roomnhouse.com
    external:     true
  - name:         GitHub
    url:          http://github.com/fashsolanki
    external:     true
pygments:         true
permalink:        pretty
markdown:         rdiscount
rdiscount:
  extensions:     [smart]
